application: yalt-tracker
version: 1
runtime: python
api_version: 1
builtins:
- datastore_admin: on

handlers:

- url: /secret
  script: yalt.py
  login: required

- url: /admin
  script: yalt.py
  login: admin

- url: /view_data
  script: yalt.py
  login: admin

- url: /new_test_point
  script: yalt.py
  login: admin

- url: /resources
  static_dir: resources

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /favicon.ico
  static_files: resources/images/favicon.ico
  upload: resources/images/favicon.ico

- url: /.*
  script: yalt.py
