application: yalt-tracker
version: 1
runtime: python
api_version: 1
builtins:
- datastore_admin: on

handlers:

- url: /secret
  script: yalt.py
  login: required

- url: /admin
  script: yalt.py
  login: admin

- url: /resources
  static_dir: resources

- url: /.*
  script: yalt.py
